#Script to remove built in appx packages from Win11 Enterprise in user context when user is logged in
#Create list of apps for removal
$AppxProvPacks = @(
    'Microsoft.BingWeather'
    'Microsoft.BingNews'
    'Microsoft.MicrosoftJournal'
    'Microsoft.GamingApp'
    'Microsoft.Getstarted'
    'Microsoft.Messaging'
    'Microsoft.Microsoft3DViewer'
    'Microsoft.MicrosoftOfficeHub'
    'Microsoft.MicrosoftSolitaireCollection'
    'Microsoft.MixedReality.Portal'
    'Microsoft.OneConnect'
    'Microsoft.People'
    'Microsoft.Print3D'
    'Microsoft.SkypeApp'
    'Microsoft.windowscommunicationsapps'
    'Microsoft.WindowsFeedbackHub'
    'Microsoft.WindowsMaps'
    'Microsoft.XboxApp'
    'Microsoft.Xbox.TCUI'
    'Microsoft.XboxGameOverlay'
    'Microsoft.XboxGamingOverlay'
    'Microsoft.XboxIdentityProvider'
    'Microsoft.XboxSpeechToTextOverlay'
    'Microsoft.YourPhone'
    'Microsoft.ZuneMusic'
    'Microsoft.ZuneVideo'
    'Microsoft.PowerAutomateDesktop'
    'MicrosoftCorporationII.MicrosoftFamily'
    'Microsoft.549981C3F5F10' #Cortana App
    'Microsoft.Windows.DevHome'
    #'Microsoft.MSPaint'
    #'Microsoft.DesktopAppInstaller'
    #'Clipchamp.Clipchamp'
    #'Microsoft.WindowsCamera'
)
#Get currently installed apps
$Apps = Get-AppxPackage -AllUsers -ErrorAction SilentlyContinue
#$PackageFullName = $Apps.PackageFullName
#Remove Appx Packages
foreach ($Package in $AppxProvPacks)
{
    if ($Apps.Name -eq $Package){
        $PackageFullName = (Get-AppxPackage -Name $Package -AllUsers).PackageFullName
        Remove-AppxPackage -Package $PackageFullName -AllUsers -ErrorAction SilentlyContinue
    }
}
#Create registry value to detect if this has been executed in already installed Windows devices, either Autopilot or not
$RegistryPath = 'HKLM:\Software\YourCompany\WinBuiltinApps'
$RegistryKey = 'AppxPacksRemoved'
$RegistryValue = '1'
#Test if registry path exist to avoid overwriting value generated by System context script
$TestPath = Test-Path -Path $RegistryPath
if($TestPath){
    New-ItemProperty -Path $RegistryPath -Name $RegistryKey -Value $RegistryValue -Force -ErrorAction SilentlyContinue
} else {
    New-Item -Path $RegistryPath -Force -ErrorAction SilentlyContinue
    New-ItemProperty -Path $RegistryPath -Name $RegistryKey -Value $RegistryValue -Force -ErrorAction SilentlyContinue
}